version: "3.9"
name: distributed_systems

# define services
services:

  Server-1:
    build: ./server
    image: server:v1
    container_name: Server-1
    networks:
      my_net:
        aliases:
          - Server-1
    hostname: Server-1
    tty: true
    environment:
      SERVER_ID: 1
      DEBUG: "true"

  Server-2:
    build: ./server
    image: server:v1
    container_name: Server-2
    networks:
      my_net:
        aliases:
          - Server-2
    hostname: Server-2
    tty: true
    environment:
      SERVER_ID: 2
      DEBUG: "true"

  Server-3:
    build: ./server
    image: server:v1
    container_name: Server-3
    networks:
      my_net:
        aliases:
          - Server-3
    hostname: Server-3
    tty: true
    environment:
      SERVER_ID: 3
      DEBUG: "true"

  Load-Balancer:
    build: ./load_balancer
    image: load:v1
    container_name: Load-Balancer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    ports:
      - "5000:5000"
    networks:
      my_net:
        aliases:
          - Load-Balancer
    hostname: Load-Balancer
    tty: true
    environment:
      DEBUG: "true"
      HASH_NUM: 2

# define a network my_net
networks:
  my_net:
    name: my_net
